# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8007f6e8ff4673057e7a8b578915effb9ffe46d96bff9013297f539ce9dbf276ca1372abf7791471894b46095af78d08139ff848b7cdb64b987a147b5e0fe921

test:
  secret_key_base: 9f7b82d104044cd7eaf0fbd1cc583a7878dd149f54d685da3692d1636013826a921700922e5d018e3090263508fae8f4df387cccbc8f2300a5011c0271b00724

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
